"""
Flask API Backend for Telco Customer Churn Prediction
Serves the ML model and connects to the premium frontend.
"""
from flask import Flask, render_template, request, jsonify
from flask_cors import CORS
import joblib
import numpy as np
import pandas as pd
import json
import os

app = Flask(__name__)
CORS(app)

# Load model artifacts
model = joblib.load('churn_model.pkl')
scaler = joblib.load('scaler.pkl')
pipeline_info = joblib.load('pipeline_info.pkl')
feature_names = pipeline_info['feature_names']

# Load feature importances and model results
with open('feature_importances.json', 'r') as f:
    feature_importances = json.load(f)

# model_results.json is optional — generated by train_model.py but not by the notebook
if os.path.exists('model_results.json'):
    with open('model_results.json', 'r') as f:
        model_results = json.load(f)
else:
    # Fallback: use pipeline_info for the best model's metrics
    model_results = {
        pipeline_info['best_model_name']: {
            'accuracy': pipeline_info['accuracy'],
            'precision': pipeline_info.get('precision', pipeline_info['accuracy']),
            'recall': pipeline_info.get('recall', pipeline_info['f1_score']),
            'f1_score': pipeline_info['f1_score'],
            'roc_auc': pipeline_info['roc_auc'],
            'cv_mean': pipeline_info.get('cv_mean', pipeline_info['roc_auc']),
        }
    }
    print("⚠️  model_results.json not found — using pipeline_info fallback")

print(f"✅ Model loaded: {pipeline_info['best_model_name']}")
print(f"   Accuracy: {pipeline_info['accuracy']:.4f}")
print(f"   ROC-AUC: {pipeline_info['roc_auc']:.4f}")


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/api/model-info', methods=['GET'])
def model_info():
    """Return model information and metrics."""
    return jsonify({
        'model_name': pipeline_info['best_model_name'],
        'accuracy': pipeline_info['accuracy'],
        'roc_auc': pipeline_info['roc_auc'],
        'f1_score': pipeline_info['f1_score'],
        'feature_importances': feature_importances,
        'model_results': model_results
    })


@app.route('/api/predict', methods=['POST'])
def predict():
    """Make a churn prediction for a customer."""
    try:
        data = request.json
        
        # Build feature vector matching the training columns
        input_data = {col: 0 for col in feature_names}
        
        # Numerical features
        input_data['Age'] = float(data.get('Age', 0))
        input_data['Number of Dependents'] = float(data.get('Number of Dependents', 0))
        input_data['Number of Referrals'] = float(data.get('Number of Referrals', 0))
        input_data['Tenure in Months'] = float(data.get('Tenure in Months', 0))
        input_data['Avg Monthly Long Distance Charges'] = float(data.get('Avg Monthly Long Distance Charges', 0))
        input_data['Avg Monthly GB Download'] = float(data.get('Avg Monthly GB Download', 0))
        input_data['Monthly Charge'] = float(data.get('Monthly Charge', 0))
        input_data['Total Charges'] = float(data.get('Total Charges', 0))
        input_data['Total Refunds'] = float(data.get('Total Refunds', 0))
        input_data['Total Extra Data Charges'] = float(data.get('Total Extra Data Charges', 0))
        input_data['Total Long Distance Charges'] = float(data.get('Total Long Distance Charges', 0))
        input_data['Total Revenue'] = float(data.get('Total Revenue', 0))
        
        # Binary/Categorical features
        binary_maps = {
            'Gender': 'Gender_Male',
            'Married': 'Married_Yes',
            'Phone Service': 'Phone Service_Yes',
            'Paperless Billing': 'Paperless Billing_Yes',
            'Online Security': 'Online Security_Yes',
            'Online Backup': 'Online Backup_Yes',
            'Device Protection Plan': 'Device Protection Plan_Yes',
            'Premium Tech Support': 'Premium Tech Support_Yes',
            'Streaming TV': 'Streaming TV_Yes',
            'Streaming Movies': 'Streaming Movies_Yes',
            'Streaming Music': 'Streaming Music_Yes',
            'Unlimited Data': 'Unlimited Data_Yes'
        }
        
        for field, col_name in binary_maps.items():
            val = data.get(field, 'No')
            if col_name in input_data:
                input_data[col_name] = 1 if val in ['Yes', 'Male'] else 0
        
        # Multiple Lines
        ml = data.get('Multiple Lines', 'No')
        if 'Multiple Lines_No phone service' in input_data:
            input_data['Multiple Lines_No phone service'] = 1 if ml == 'No phone service' else 0
        if 'Multiple Lines_Yes' in input_data:
            input_data['Multiple Lines_Yes'] = 1 if ml == 'Yes' else 0
        
        # Internet Service
        inet_svc = data.get('Internet Service', 'Yes')
        if 'Internet Service_No' in input_data:
            input_data['Internet Service_No'] = 1 if inet_svc == 'No' else 0
        
        # Internet Type
        inet_type = data.get('Internet Type', 'Cable')
        if 'Internet Type_DSL' in input_data:
            input_data['Internet Type_DSL'] = 1 if inet_type == 'DSL' else 0
        if 'Internet Type_Fiber Optic' in input_data:
            input_data['Internet Type_Fiber Optic'] = 1 if inet_type == 'Fiber Optic' else 0
        
        # Contract
        contract = data.get('Contract', 'Month-to-Month')
        if 'Contract_One Year' in input_data:
            input_data['Contract_One Year'] = 1 if contract == 'One Year' else 0
        if 'Contract_Two Year' in input_data:
            input_data['Contract_Two Year'] = 1 if contract == 'Two Year' else 0
        
        # Payment Method
        pm = data.get('Payment Method', 'Credit Card')
        if 'Payment Method_Bank Withdrawal' in input_data:
            input_data['Payment Method_Bank Withdrawal'] = 1 if pm == 'Bank Withdrawal' else 0
        if 'Payment Method_Credit Card' in input_data:
            input_data['Payment Method_Credit Card'] = 1 if pm == 'Credit Card' else 0
        if 'Payment Method_Mailed Check' in input_data:
            input_data['Payment Method_Mailed Check'] = 1 if pm == 'Mailed Check' else 0
        
        # Offer
        offer = data.get('Offer', 'None')
        if 'Offer_None' in input_data:
            input_data['Offer_None'] = 1 if offer == 'None' else 0
        elif 'Offer' in input_data:
            # Handle if Offer is encoded differently
            for offer_val in ['A', 'B', 'C', 'D', 'E', 'None']:
                col = f'Offer_{offer_val}'
                if col in input_data:
                    input_data[col] = 1 if offer == offer_val else 0
        
        # City encoding (create dummy for commonly occurring cities or leave as 0)
        city = data.get('City', 'Unknown')
        # City columns would be added dynamically based on training data
        
        # Create DataFrame with correct column order
        input_df = pd.DataFrame([input_data], columns=feature_names)
        
        # Scale
        input_scaled = scaler.transform(input_df)
        
        # Predict
        prediction = int(model.predict(input_scaled)[0])
        probability = float(model.predict_proba(input_scaled)[0][1])
        
        # Get risk factors
        risk_factors = []
        tenure = float(data.get('Tenure in Months', 0))
        monthly_charge = float(data.get('Monthly Charge', 0))
        
        if tenure < 12:
            risk_factors.append('New customer (tenure < 12 months)')
        if monthly_charge > 80:
            risk_factors.append('High monthly charges (> $80)')
        if contract == 'Month-to-Month':
            risk_factors.append('Month-to-Month contract (less committed)')
        if inet_type == 'Fiber Optic':
            risk_factors.append('Fiber Optic internet user')
        if data.get('Online Security') == 'No':
            risk_factors.append('No Online Security service')
        if data.get('Premium Tech Support') == 'No':
            risk_factors.append('No Premium Tech Support')
        if pm == 'Bank Withdrawal':
            risk_factors.append('Bank Withdrawal payment method')
        if data.get('Paperless Billing') == 'Yes':
            risk_factors.append('Paperless Billing enabled')
        if float(data.get('Number of Referrals', 0)) == 0:
            risk_factors.append('No referrals (lower engagement)')
        
        return jsonify({
            'success': True,
            'prediction': 'Churned' if prediction == 1 else 'Retained',
            'churn_probability': round(probability * 100, 2),
            'retention_probability': round((1 - probability) * 100, 2),
            'risk_level': 'High' if probability > 0.7 else ('Medium' if probability > 0.4 else 'Low'),
            'risk_factors': risk_factors
        })
        
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 400


if __name__ == '__main__':
    app.run(debug=True, port=5000)
