"""
Flask API Backend for Telco Customer Churn Prediction
Serves the ML model and connects to the premium frontend.
"""
from flask import Flask, render_template, request, jsonify
from flask_cors import CORS
import joblib
import numpy as np
import pandas as pd
import json
import os

app = Flask(__name__)
CORS(app)

# Load model artifacts
model = joblib.load('churn_model.pkl')
scaler = joblib.load('scaler.pkl')
pipeline_info = joblib.load('pipeline_info.pkl')
feature_names = pipeline_info['feature_names']

# Load feature importances and model results
with open('feature_importances.json', 'r') as f:
    feature_importances = json.load(f)

# model_results.json is optional — generated by train_model.py but not by the notebook
if os.path.exists('model_results.json'):
    with open('model_results.json', 'r') as f:
        model_results = json.load(f)
else:
    # Fallback: use pipeline_info for the best model's metrics
    model_results = {
        pipeline_info['best_model_name']: {
            'accuracy': pipeline_info['accuracy'],
            'precision': pipeline_info.get('precision', pipeline_info['accuracy']),
            'recall': pipeline_info.get('recall', pipeline_info['f1_score']),
            'f1_score': pipeline_info['f1_score'],
            'roc_auc': pipeline_info['roc_auc'],
            'cv_mean': pipeline_info.get('cv_mean', pipeline_info['roc_auc']),
        }
    }
    print("⚠️  model_results.json not found — using pipeline_info fallback")

print(f"✅ Model loaded: {pipeline_info['best_model_name']}")
print(f"   Accuracy: {pipeline_info['accuracy']:.4f}")
print(f"   ROC-AUC: {pipeline_info['roc_auc']:.4f}")


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/api/model-info', methods=['GET'])
def model_info():
    """Return model information and metrics."""
    return jsonify({
        'model_name': pipeline_info['best_model_name'],
        'accuracy': pipeline_info['accuracy'],
        'roc_auc': pipeline_info['roc_auc'],
        'f1_score': pipeline_info['f1_score'],
        'feature_importances': feature_importances,
        'model_results': model_results
    })


@app.route('/api/predict', methods=['POST'])
def predict():
    """Make a churn prediction for a customer."""
    try:
        data = request.json
        
        # Build feature vector matching the training columns
        input_data = {col: 0 for col in feature_names}
        
        # Numerical features
        input_data['tenure'] = float(data.get('tenure', 0))
        input_data['MonthlyCharges'] = float(data.get('MonthlyCharges', 0))
        input_data['TotalCharges'] = float(data.get('TotalCharges', 0))
        
        # Binary features (Yes/No → _Yes columns from get_dummies with drop_first=True)
        binary_maps = {
            'gender': 'gender_Male',
            'SeniorCitizen': 'SeniorCitizen_Yes',
            'Partner': 'Partner_Yes',
            'Dependents': 'Dependents_Yes',
            'PhoneService': 'PhoneService_Yes',
            'PaperlessBilling': 'PaperlessBilling_Yes'
        }
        
        for field, col_name in binary_maps.items():
            val = data.get(field, 'No')
            if col_name in input_data:
                input_data[col_name] = 1 if val == 'Yes' or val == 'Male' else 0
        
        # MultipleLines
        ml = data.get('MultipleLines', 'No')
        if 'MultipleLines_No phone service' in input_data:
            input_data['MultipleLines_No phone service'] = 1 if ml == 'No phone service' else 0
        if 'MultipleLines_Yes' in input_data:
            input_data['MultipleLines_Yes'] = 1 if ml == 'Yes' else 0
        
        # InternetService
        inet = data.get('InternetService', 'No')
        if 'InternetService_Fiber optic' in input_data:
            input_data['InternetService_Fiber optic'] = 1 if inet == 'Fiber optic' else 0
        if 'InternetService_No' in input_data:
            input_data['InternetService_No'] = 1 if inet == 'No' else 0
        
        # Internet-dependent services
        inet_services = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 
                         'TechSupport', 'StreamingTV', 'StreamingMovies']
        for svc in inet_services:
            val = data.get(svc, 'No')
            col_noint = f'{svc}_No internet service'
            col_yes = f'{svc}_Yes'
            if col_noint in input_data:
                input_data[col_noint] = 1 if val == 'No internet service' else 0
            if col_yes in input_data:
                input_data[col_yes] = 1 if val == 'Yes' else 0
        
        # Contract
        contract = data.get('Contract', 'Month-to-month')
        if 'Contract_One year' in input_data:
            input_data['Contract_One year'] = 1 if contract == 'One year' else 0
        if 'Contract_Two year' in input_data:
            input_data['Contract_Two year'] = 1 if contract == 'Two year' else 0
        
        # PaymentMethod
        pm = data.get('PaymentMethod', 'Electronic check')
        if 'PaymentMethod_Credit card (automatic)' in input_data:
            input_data['PaymentMethod_Credit card (automatic)'] = 1 if pm == 'Credit card (automatic)' else 0
        if 'PaymentMethod_Electronic check' in input_data:
            input_data['PaymentMethod_Electronic check'] = 1 if pm == 'Electronic check' else 0
        if 'PaymentMethod_Mailed check' in input_data:
            input_data['PaymentMethod_Mailed check'] = 1 if pm == 'Mailed check' else 0
        
        # Create DataFrame with correct column order
        input_df = pd.DataFrame([input_data], columns=feature_names)
        
        # Scale
        input_scaled = scaler.transform(input_df)
        
        # Predict
        prediction = int(model.predict(input_scaled)[0])
        probability = float(model.predict_proba(input_scaled)[0][1])
        
        # Get risk factors
        risk_factors = []
        if float(data.get('tenure', 0)) < 12:
            risk_factors.append('Short tenure (< 12 months)')
        if float(data.get('MonthlyCharges', 0)) > 70:
            risk_factors.append('High monthly charges')
        if contract == 'Month-to-month':
            risk_factors.append('Month-to-month contract')
        if inet == 'Fiber optic':
            risk_factors.append('Fiber optic internet')
        if data.get('OnlineSecurity', 'No') == 'No':
            risk_factors.append('No online security')
        if data.get('TechSupport', 'No') == 'No':
            risk_factors.append('No tech support')
        if pm == 'Electronic check':
            risk_factors.append('Electronic check payment')
        if data.get('PaperlessBilling', 'No') == 'Yes':
            risk_factors.append('Paperless billing')
        
        return jsonify({
            'success': True,
            'prediction': 'Churn' if prediction == 1 else 'No Churn',
            'churn_probability': round(probability * 100, 2),
            'retention_probability': round((1 - probability) * 100, 2),
            'risk_level': 'High' if probability > 0.7 else ('Medium' if probability > 0.4 else 'Low'),
            'risk_factors': risk_factors
        })
        
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 400


if __name__ == '__main__':
    app.run(debug=True, port=5000)
